import { CategoryOptionsEnum } from "./CategoryOptionsEnum"
import { CountryOptionsEnum } from "./CountryOptionsEnum"
import { LanguageOptionsEnum } from "./LanguageOptionsEnum"

export const CountryOptionsMapping: Record<CountryOptionsEnum, string> = {

    [CountryOptionsEnum.Argentina]: "Argentina",
    [CountryOptionsEnum.Australia]: "Australia",
    [CountryOptionsEnum.Austria]: "Austria",
    [CountryOptionsEnum.Belgium]: "Belgium",
    [CountryOptionsEnum.Brazil]: "Brazil",
    [CountryOptionsEnum.Bulgaria]: "Bulgaria",
    [CountryOptionsEnum.Canada]: "Canada",
    [CountryOptionsEnum.China]: "China",
    [CountryOptionsEnum.Colombia]: "Colombia",
    [CountryOptionsEnum.Cuba]: "Cuba",
    [CountryOptionsEnum.Czech_republic]: "Czech Republic",
    [CountryOptionsEnum.Egypt]: "Egypt",
    [CountryOptionsEnum.France]: "France",
    [CountryOptionsEnum.Germany]: "Germany",
    [CountryOptionsEnum.Greece]: "Greece",
    [CountryOptionsEnum.Hong_kong]: "Hong kong",
    [CountryOptionsEnum.Hungary]: "Hungary",
    [CountryOptionsEnum.India]: "India",
    [CountryOptionsEnum.Indonesia]: "Indonesia",
    [CountryOptionsEnum.Ireland]: "Ireland",
    [CountryOptionsEnum.Israel]: "Israel",
    [CountryOptionsEnum.Italy]: "Italy",
    [CountryOptionsEnum.Japan]: "Japan",
    [CountryOptionsEnum.Latvia]: "Latvia",
    [CountryOptionsEnum.Lebanon]: "Lebanon",
    [CountryOptionsEnum.Lithuania]: "Lithuania",
    [CountryOptionsEnum.Malaysia]: "Malaysia",
    [CountryOptionsEnum.Mexico]: "Mexico",
    [CountryOptionsEnum.Morocco]: "Morocco",
    [CountryOptionsEnum.Netherland]: "Netherland",
    [CountryOptionsEnum.New_zealand]: "New Zealand",
    [CountryOptionsEnum.Nigeria]: "Nigeria",
    [CountryOptionsEnum.North_korea]: "North Korea",
    [CountryOptionsEnum.Norway]: "Norway",
    [CountryOptionsEnum.Pakistan]: "Pakistan",
    [CountryOptionsEnum.Philippines]: "Philippines",
    [CountryOptionsEnum.Poland]: "Poland",
    [CountryOptionsEnum.Portugal]: "Portugal",
    [CountryOptionsEnum.Romania]: "Romania",
    [CountryOptionsEnum.Russia]: "Russia",
    [CountryOptionsEnum.Saudi_arabia]: "Saudi Arabia",
    [CountryOptionsEnum.Serbia]: "Serbia",
    [CountryOptionsEnum.Singapore]: "Singapore",
    [CountryOptionsEnum.Slovakia]: "Slovakia",
    [CountryOptionsEnum.Slovenia]: "Slovenia",
    [CountryOptionsEnum.South_africa]: "South Africa",
    [CountryOptionsEnum.South_korea]: "South Korea",
    [CountryOptionsEnum.Spain]: "Spain",
    [CountryOptionsEnum.Sweden]: "Sweden",
    [CountryOptionsEnum.Switzerland]: "Switzerland",
    [CountryOptionsEnum.Taiwan]: "Taiwan",
    [CountryOptionsEnum.Thailand]: "Thailand",
    [CountryOptionsEnum.Turkey]: "Turkey",
    [CountryOptionsEnum.Ukraine]: "Ukraine",
    [CountryOptionsEnum.United_arab_emirates]: "United Arab Emirates",
    [CountryOptionsEnum.United_kingdom]: "United Kingdom",
    [CountryOptionsEnum.United_states_of_america]: "United States Of America",
    [CountryOptionsEnum.Venezuela]: "Venezuela"
}


export const LanguageOptionsMapping: Record<LanguageOptionsEnum, string> = {

    [LanguageOptionsEnum.Arabic]: "Arabic",
    [LanguageOptionsEnum.Bosnian]: "Bosnian",
    [LanguageOptionsEnum.Bulgarian]: "Bulgarian",
    [LanguageOptionsEnum.Chinese]: "Chinese",
    [LanguageOptionsEnum.Croatian]: "Croatian",
    [LanguageOptionsEnum.Czech]: "Czech",
    [LanguageOptionsEnum.Dutch]: "Dutch",
    [LanguageOptionsEnum.English]: "English",
    [LanguageOptionsEnum.French]: "French",
    [LanguageOptionsEnum.German]: "German",
    [LanguageOptionsEnum.Greek]: "Greek",
    [LanguageOptionsEnum.Hebrew]: "Hebrew",
    [LanguageOptionsEnum.Hindi]: "Hindi",
    [LanguageOptionsEnum.Hungarian]: "Hungarian",
    [LanguageOptionsEnum.Indonesian]: "Indonesian",
    [LanguageOptionsEnum.Italian]: "Italian",
    [LanguageOptionsEnum.Japanese]: "Japanese",
    [LanguageOptionsEnum.Korean]: "Korean",
    [LanguageOptionsEnum.Latvian]: "Latvian",
    [LanguageOptionsEnum.Lithuanian]: "Lithuanian",
    [LanguageOptionsEnum.Malay]: "Malay",
    [LanguageOptionsEnum.Norwegian]: "Norwegian",
    [LanguageOptionsEnum.Polish]: "Polish",
    [LanguageOptionsEnum.Portuguese]: "Portuguese",
    [LanguageOptionsEnum.Romanian]: "Romanian",
    [LanguageOptionsEnum.Russian]: "Russian",
    [LanguageOptionsEnum.Serbian]: "Serbian",
    [LanguageOptionsEnum.Slovak]: "Slovak",
    [LanguageOptionsEnum.Slovenian]: "Slovenian",
    [LanguageOptionsEnum.Spanish]: "Spanish",
    [LanguageOptionsEnum.Swedish]: "Swedish",
    [LanguageOptionsEnum.Thai]: "Thai",
    [LanguageOptionsEnum.Turkish]: "Turkish",
    [LanguageOptionsEnum.Ukrainian]: "Ukrainian",

}